# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1351, 895)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Mainwindow = QtWidgets.QLabel(self.centralwidget)
        self.Mainwindow.setGeometry(QtCore.QRect(0, 0, 1351, 891))
        self.Mainwindow.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:2px solid white;")
        self.Mainwindow.setObjectName("Mainwindow")
        self.Gif1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif1.setGeometry(QtCore.QRect(10, 10, 661, 611))
        self.Gif1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:1px solid white;")
        self.Gif1.setText("")
        self.Gif1.setPixmap(QtGui.QPixmap("G.U.I. Material/B.G/1.gif"))
        self.Gif1.setScaledContents(True)
        self.Gif1.setObjectName("Gif1")
        self.Gif2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif2.setGeometry(QtCore.QRect(680, 10, 661, 361))
        self.Gif2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:1px solid white;")
        self.Gif2.setText("")
        self.Gif2.setPixmap(QtGui.QPixmap("G.U.I. Material/VoiceReg/Siri_1.gif"))
        self.Gif2.setScaledContents(True)
        self.Gif2.setObjectName("Gif2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 380, 661, 231))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:1px solid white;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("G.U.I. Material/ExtraGui/initial.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(920, 780, 181, 51))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"border:2px solid white;")

        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1130, 780, 181, 51))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"border:2px solid white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 770, 221, 61))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(270, 770, 221, 61))
        self.textBrowser_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
                
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Mainwindow.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "QUIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
